### ISSUE TITLE
missing funds

### ISSUE THREAD

**Issue by Maxi9999** [Sifchain/Support-Tickets#256] opened 2022-02-20 10:05 UTC
**Describe the bug**

A Detailed description of the issue (what happened, token affected and token amount)

**How to Reproduce**

4. See error "..."

**Expected behavior**
<Please write a clear and detailed description of what you expected to happen.>

**TX Hashes** (if applicable)

Please provide links to transaction hashes of the import / export issues you are facing

**Addresses** (if applicable
<Please provide links to your addresses (both of Sifchain and external chain)>

**Error logs**
<Please provide links to your addresses (both of Sifchain and external chain)>

**Screenshots**

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by Maxi9999** [comment] 2022-02-20 10:07
LALALALA — Today at 5:52 PM
Well what is the issue you are having?
I can forward it to the devs if it's a bug
Max07 — Today at 5:53 PM
missing aprox 7000
LALALALA — Today at 5:53 PM
7000 what?
rowan?
Max07 — Today at 5:53 PM
dollars
not sure what happened
LALALALA — Today at 5:53 PM
Ok so more details please
Max07 — Today at 5:54 PM
ok I had around 17000 in a pool and  1700 in another
One pool converted it into ust
LALALALA — Today at 5:55 PM
ok
Max07 — Today at 5:55 PM
17000
LALALALA — Today at 5:55 PM
ok so I will forward this to devs but please answer these questions
Please write a detailed description of the issue.

What is the name and amount of the token affected?

What is your Sifchain address?

What is your address on the other chain?

What is the link to the transaction has you are having problem with?

Are there any error logs you can share?
Max07 — Today at 5:55 PM
then I transfered in 120000 rowan in yesterday
and sent that to ust
LALALALA — Today at 5:55 PM
yea yesterday we were having transferring issues but that should have all been corrected
and refunded
Max07 — Today at 5:56 PM
then put it all back into the pools but im now short the value of 120,000 rowan
not there
I want to put in a pool now
But it's not anywhere
LALALALA — Today at 5:59 PM
https://github.com/Sifchain/Support-Tickets/issues
GitHub
[Issues · Sifchain/Support-Tickets](https://github.com/Sifchain/Support-Tickets/issues)[](https://opengraph.githubassets.com/8724406b60040b94c4819539f7a582c04d7bdc5db86cea22cc7c646e4168ccb5/Sifchain/Support-Tickets)
Here we can hendle support tickets raised from the community - Issues · Sifchain/Support-Tickets

Open a new ticket there. That will go immediately to the devs
This sounds like something they need to know about. They will get your money back.
Max07 — Today at 6:00 PM
That takes me somewhere to open an account
github
LALALALA — Today at 6:01 PM
github, yea you need to make a github account to communicate with the devs dire4ctly
I can make the ticket for you but it is better when you talk to them youself sometimes
to explain everything in detail rather than having a middleman
Max07 — Today at 6:01 PM
make a ticket also please

**Comment by Maxi9999** [comment] 2022-02-20 11:17
I don't know what happened exactly there is no transaction history that i can find on sifchain I think i can see the transaction going from osmosis to sif and I got a confirmation and then going from rowan to ust I don't see

**Comment by Maxi9999** [comment] 2022-02-20 11:18
sif1fd8kd7qkneye4y96slq8992r34lt0wfeqr5uq8

**Comment by Maxi9999** [comment] 2022-02-20 11:19
120000 rowan missing

**Comment by Maxi9999** [comment] 2022-02-20 11:56
Or equivalent in ust not sure which

**Comment by lufa23** [comment] 2022-02-21 13:20
hey @Maxi9999 i would need some more details... looking at the [block explorer](https://www.mintscan.io/sifchain/account/sif1fd8kd7qkneye4y96slq8992r34lt0wfeqr5uq8) and at what you are saying it is not clear to me what's the issue is..

Can you please provide a clear descriptions with steps, specifying pools, amount and action performed? Without a clear description it's very difficult for us to help you out..

For example:
_1) I added 17000 worth of Rowan in the LUNA- ROWAN pool, added symmetrically on this date (as you can see from the tx hash ....) and 1700 worth of rowan in the ATOM-ROWAN pool, that i added on ... , with tx hash ...
2) Then i exported 120000 rowan to OSMOSIS, as you can see in tx hash ...
3) then i swapped .... rowan for usdt on SIfchain (as you can see in tx hash..)_
4) When looking at the balance of my sifchain address sif.... i expected to see .... but i only have ....

**Comment by Maxi9999** [comment] 2022-02-21 13:25
Not sure myself I had an eye infection so could not see well
I have a confirmation that the transfer of 120,000 rowan was sent to sifchain then I bought ust in the same amount on sifchain I saw the confirmation that the transaction went through turned off computer 2 days later I don't see it

**Comment by Maxi9999** [comment] 2022-02-21 15:07
There does not appear to be any kind of statement that i can find to tell me what happened
I already had 17000ust when I added more

**Comment by lufa23** [comment] 2022-02-21 16:14
"I have a confirmation that the transfer of 120,000 rowan was sent to sifchain "Can you provide us with the transaction hash?

**Comment by lufa23** [comment] 2022-02-21 16:22
if your issue is to import assets from Terra to Sifchain or viceversa, keep in mind that there are currently issues with relaying packets between Terra and Sifchain.. You can have a look at [this announcement](https://discord.com/channels/769209144515100693/930443229034319872/944032937370877964)

**Comment by Maxi9999** [comment] 2022-02-21 23:52
I already gave you this


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Maxi9999** [comment] 2022-02-21 23:53
I can not find where on siftchain transaction history for anything at all

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Maxi9999** [comment] 2022-02-21 23:56
> "I have a confirmation that the transfer of 120,000 rowan was sent to sifchain "Can you provide us with the transaction hash?

1C05DC7FE92C57946A51D9DF1F1374F1A955C03F685F182C520575E1DA856551

**Comment by Maxi9999** [comment] 2022-02-21 23:57
> if your issue is to import assets from Terra to Sifchain or viceversa, keep in mind that there are currently issues with relaying packets between Terra and Sifchain.. You can have a look at [this announcement](https://discord.com/channels/769209144515100693/930443229034319872/944032937370877964)

I want to know not speculate

**Comment by emperorjm** [comment] 2022-02-22 02:43
Hi @Maxi9999. Based on my checks you had 27,509.042786 UST which you swapped for other tokens over the last 2-3 days. The list of transactions are as follows:

You swapped 120,506.680125004361036665ROWAN to 9,254.951136UST https://www.mintscan.io/sifchain/txs/BBFD3CE48FB3721877171E6C6B5705F40EC6A4B7686164BFE836147AB66C0516. Then you swapped 13,754.000000UST for 129,976.084486177809010000ROWAN here https://www.mintscan.io/sifchain/txs/8C1EEE46B9D46162D1C363FF317A51EEDD082600017849817ED5E17F54467E66 and then you swapped 13,755.042786UST for 341.317852ATOM here https://www.mintscan.io/sifchain/txs/CC00C73E34E97E0A30B175D8A403D6E45951BFE91CE2964FF625E1A6858DDFE3. This totals 27,509.042786 UST that you swapped for other tokens which is the amount he is saying he is not seeing.

You said you had 17k and you couldn't account for 9k UST. The above transactions showed what happened to those tokens.

I'll close this ticket based on the information outlined above.

**Closed as completed by emperorjm** 2022-02-22 02:43 UTC

**Comment by Maxi9999** [comment] 2022-02-22 02:57
I don't care if I swapped I would still have 27k in other tokens if that were true but I don't

**Comment by Maxi9999** [comment] 2022-02-22 02:58
it only adds up to 17 not 27
I did not transfer out

**Comment by Maxi9999** [comment] 2022-02-22 03:04
Escalate this please

**Comment by Maxi9999** [comment] 2022-02-22 03:04
I need a manager

**Comment by Maxi9999** [comment] 2022-02-22 03:06
Urgent

**Comment by Maxi9999** [comment] 2022-02-22 04:30
I figured it out
Ok I found the problem
I got the money from osmosis np
I transferred the pool to ust np
27,000 confirmed np
But when I went back in the pool it bougt atom at 40.50cents aprox when atom was trading at 25.00 Big Problem
Also bought rowan at .1058 aprox when rowan was trading at .078 big problem
That's the error I way overpaid for everything.....why?
This is supposed to be automatic
So to me you have a bug somewhere, your dev confirmed I had 27k so one of two things happened.
1 your program did not recognize 9k of my money.
2 It did not buy properly way overspending my money
But now that we know we need to get this fixed now, please
This is also costing me about 100 a day in missing interest so time here is a big deal, thanks
