### ISSUE TITLE
Unable to add Liquidity Addition on Cosmostation

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#389] opened 2022-06-10 16:57 UTC
**Description:**
Unable to add liquidity symmetrically in Cosmostation for the SHIB pool, as an error log is triggered as the liquidity addition is asymmetric
![Screenshot_20220610-015152](https://user-images.githubusercontent.com/67415638/173115440-b2e96342-24ca-4201-aa26-d70f3d55e593.png)

**Ways to reproduce it:**
Adding liquidity symmetrically on the SHIB - ROWAN pool

**Comment by lufa23** [comment] 2022-06-10 17:03
Cosmostation team has been contacted

**Comment by Stellar-tickets** [comment] 2022-06-11 21:05
Elon: ok, lufa. thanks

**Comment by Stellar-tickets** [comment] 2022-06-11 21:05
Elon: how I close the ticket?

**Comment by Stellar-tickets** [comment] 2022-06-13 21:35
lufa23: !!close

**Comment by lufa23** [comment] 2022-06-17 10:50
still pending on Cosmostation's answer.
I pinged them again

**Comment by lufa23** [comment] 2022-06-30 16:06
asymmetric liquidity will be enabled again this week

**Comment by lufa23** [comment] 2022-07-04 16:07
the enabling of asymmetric liquidity adds is on pause at the moment. To tackle this issue, it is suggested to try multiple times

**Comment by lufa23** [comment] 2022-08-22 12:04
to check if Formula has been updated in order to tackle the issue for Low Liquidity Pools

**Comment by lufa23** [comment] 2022-08-31 16:43
closing as asymmetric adds are currently disabled. Flat fees is introduced in order to re-enable asymmetric adds. The issue is not expected to appear once asymmetric adds are re-enabled

**Closed as completed by lufa23** 2022-08-31 16:43 UTC
Labels: Developer Relations Team, Level 2 Support (DevRels Team), H
