### ISSUE TITLE
Rewards Issue

### ISSUE THREAD

**Issue by ivorychristine** [Sifchain/Support-Tickets#191] opened 2021-12-30 14:59 UTC
I claimed the rewards on Monday and it showed as pending dispensation. Out of which 30% was dispensed and i was able to see on my wallet but 70% of the amount still shows as pending dispensation. The expected rewards were approximately 3200 and dispensed amout was around 1000. the pending dispensation is 2123.79. 
I can see that as total pending dispensation also in the Pools of the People(v2) — 997 and Sif’s Expansion - 1126.59

how can i get the transaction has of my claim? please help

sifchain address sif1lspy7yu506jz2qa0npwuut22qayde49uaqwf77
Transaction Hash: https://www.mintscan.io/sifchain/txs/A16FE29A5ABF2590C5429239B900D6F7C4EBEF563010330B350CDE1DC8B4FA91
User: evolution4good

**Comment by lufa23** [comment] 2021-12-30 16:30
it seems to be a duplicate of [this issue](https://github.com/Sifchain/Support-Tickets/issues/186)

**Closed by lufa23** 2021-12-30 16:30 UTC
Labels: Level 1 Support (CMs Team)
