### ISSUE TITLE
BUG: swap issue

### ISSUE THREAD

**Issue by dana-nomad** [Sifchain/Support-Tickets#359] opened 2022-05-22 21:51 UTC
Describe the bug
Inconsistent and Inaccurate swap quotation in the Sifchain 'Swap' UI. This issue arise after the PMTP upgrades, where the quoted price no longer takes the two variables, Liquidity Provider Fee and Price Impact into consideration as before. For instance, consider paring METIS/USDT, the quoted receiving USDT is 30.006501 shown in the Figure below, while upon proceeding with the Swap, the confirmation window displays 29.939951. 

Why is this a bug?
In the confirmation prompt window, the quoted amount 29.939951 is clearly different than the 'USDT per METIS' which is 30.006501.

Expected Behavior
The quoted USDT value in the confirmation window is the accurate but it should be include before the confirmation prompt as most users only read information presented by them in the first time. And, no DEX expect users to deduct the Liquidity Provider Fee and Price Impact from the quoted amount in the 'Swap' UI.

Consequences If Ignore
1. Unintended and unreasonable loss of fund due to inaccurate quote, i.e. user expect to pay 250USDT for 10 ATOM while receiving only 9.5 ATOM.
2. Lower arbitrage opportunities. The arbitrage opportunity in 'Pool Stats' UI rendered inaccurate as it needs to be offset by both 'Liquidity Provider Fee' and 'Price Impact' which often account for 1-2% depending on the pool depth.
3. Lower trading fees generated. As a consequence of lower arbitrage activities.

Steps to reproduce
1. Proceed to Sifdex Swap UI.
2. Trade with any pairing.

Screenshots
The first Figure depict the 'Swap UI' where METIS/USDT is quoted, while the second shows that of quoted amount in the confirmation window.
![22222222](https://user-images.githubusercontent.com/94938706/169717461-645ec294-f022-4040-b82d-4ac270966497.png)
![111111](https://user-images.githubusercontent.com/94938706/169717462-0f6a5065-1d91-4491-90c9-7ffefea3a3ea.png)

**Comment by lufa23** [comment] 2022-05-23 20:47
thanks for the accurate report, let us look into it

**Comment by lufa23** [comment] 2022-05-23 21:08
can you confirm the issue persists? i just tried with a smaller amount and it seems to be working good

**Comment by Alex00000090** [comment] 2022-05-27 09:58
Yes, certain.

**Comment by bksifchain** [comment] 2022-05-27 12:30
This is not a bug. This is how the swap input and confirmation modal were implemented during the PMTP refactor. We will look into ways to address this, however the confirmation modal is acting exactly as described - it confirms with the user, the closest swap amount they will receive. In the initial swap input component, the results displayed do not account for price impact and LP fees, so in the confirmation modal, we now show the user the most accurate results we can describe (and additionally showing min received to account for potential slippage). Moving this calculation back to the swap input component is not as straightforward as it seems since the inputs for From > To are auto-calculated based on whatever values you put into them. Reverse calculating a value from To > From (which would automatically includes the LP fee and price impact) would require additional logic that was removed during the PMTP refactor. 

If the real issue here is misrepresenting arbitrage opportunities, then yes, we could look into a feature enhancement to incorporate those fees into that arb % calculation.

**Comment by Alex00000090** [comment] 2022-05-30 16:05
Any follow-up on this? It's crucial.

**Comment by Alex00000090** [comment] 2022-05-30 16:27
Whether this is a bug or not, no user would perform any swap on a DEX with incorrect information, what is the point of having two layers of confirmation where the first is redundant? Otherwise, why would Sifchain implements the other way before the PMTP? From a user perspective, conveniency and accuracy are the prioritized criteria, therefore the information presented should be simplified and unified. Besides, the suggested quote in the 2nd layer of confirmation is significantly less than the actual receiving amount relative to before PMTP, where the main factor of difference before PMTP is mostly coming from the sudden price change. In other words, the DEX is now worse than OSMOSIS in terms of daily usages (Yes, I would vouch for Sifchain every time over OSMOSIS before PMTP due to its accuracy in the quoting). Furthermore, it isn't just a misrepresenting arbitrage opportunity, assuming a user would like to purchase 25 ATOM with USDT, if the quote does not factor in liquidity provider fees and price impact, the user will end up with significantly less than the desired ATOM. Then, to acquire 25 ATOM, the user would have to personally input for 25.5 ATOM to account for the difference, I would certainly hope this isn't the user experience Sifchain strived to bring. Last but not least, from someone whom have been arbitraging since 2021 September, I haven't enjoy a single swap on Sifchain after PMTP, and the fact the matter is in lack of awareness just show how the majority of the user are liquidity providers instead of traders, you might want to fix this as soon as possible otherwise inflation is the only source sustaining the LP paid out.

**Comment by lufa23** [comment] 2022-06-02 16:53
hey thanks for your feedback, it really helps
We have noted it into the backlog, we're gonna have a closer look on this

**Comment by Alex00000090** [comment] 2022-06-08 06:31
It's been almost a week, any updates?

**Comment by lufa23** [comment] 2022-06-13 21:52
hey, we have noted it down as a feature to add back
@bksifchain

**Comment by lufa23** [comment] 2022-06-14 20:35
hey, we are looking to enhance this item with the Frontend v3 release

**Closed as completed** 2022-09-16 15:06 UTC
Labels: Developer Relations Team, Level 2 Support (DevRels Team), Front End Team, M
