### ISSUE TITLE
Import / Export issue

### ISSUE THREAD

**Issue by cook0991** [Sifchain/Support-Tickets#196] opened 2022-01-05 05:00 UTC
## Describe the bug

failed imports aave to sifchain, fail tx on etherscan after a minute or so, saying insufficient gas,even tho high gas was selected

## How to Reproduce

1. connect metamask and keplr to sifchain dex
2.import
3. tx shows fail on etherscan
4. but continues on sifchain to the 50 confirms then, obviously nothing as the tx had failed eth side
4. 

## Expected behaviour

expected behaviour would be aave imported to sifchain and farmed :)

am i able to send tx hashes and wallet addresses via email or secure msging?

thanks for your help.

eth import is my only issue, importing atom from osmosis and other tokens works very well, just pretty annoying to get a failed tx on 2 seperate wallets on different browsers, gets very expensive, as we all know.

tia

**Comment by lufa23** [comment] 2022-01-05 20:30
hey sure, send me a DM with the TX HASH on discord
My user handle is lufa23#0240 :)

**Comment by lufa23** [comment] 2022-01-07 13:20
hey @cook0991 , is your issue solved? I did not receive any message on Discord..

**Comment by lufa23** [comment] 2022-01-11 14:12
i assume that the issue is solved, closing the ticket for now

**Closed by lufa23** 2022-01-11 14:12 UTC
Labels: Developer Relations Team, Level 1 Support (CMs Team), Level 2 Support (DevRels Team)
