### ISSUE TITLE
ticket-27

### ISSUE THREAD

**Issue by Stellar-tickets** [Sifchain/Support-Tickets#268] opened 2022-03-09 16:28 UTC
**Please write a detailed description of the issue.**
Not received full reward for this week.

**What is the name and amount of the token affected?**
sif1tc04s3qm00fyhllzrm4e3lrdrhzx798x3q7s84

I got around 6k rowans. Should get cca 20k.

**What is your Sifchain address?**
sif1tc04s3qm00fyhllzrm4e3lrdrhzx798x3q7s84

**What is your address on the other chain?**
/

**What is the link to the transaction has you are having problem with?**
Reward dispensation issue

**Are there any error logs you can share?**
/

**Comment by emperorjm** [comment] 2022-03-09 16:37
This issue is a duplicate of this issue https://github.com/Sifchain/Support-Tickets/issues/267

**Closed as completed by emperorjm** 2022-03-09 16:37 UTC
Labels: Developer Relations Team, Level 2 Support (DevRels Team)
